"""move hold_point_verified to checklist_items

Revision ID: ca24eea873d8
Revises: d5f2afdab618
Create Date: 2026-06-02 12:21:09.704457
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca24eea873d8'
down_revision: Union[str, None] = 'd5f2afdab618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_completions', 'hold_point_verified_at')
    op.drop_column('checklist_completions', 'hold_point_verified_by')
    op.add_column('checklist_items', sa.Column('hold_point_verified_by', sa.String(length=255), nullable=True))
    op.add_column('checklist_items', sa.Column('hold_point_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_items', 'hold_point_verified_at')
    op.drop_column('checklist_items', 'hold_point_verified_by')
    op.add_column('checklist_completions', sa.Column('hold_point_verified_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('checklist_completions', sa.Column('hold_point_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
